---
language: python
services: docker

env:
  global:
    - ROLE_NAME: consul
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: amazonlinux2
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install -r requirements.txt

before_script:
  - cd ../
  - mv ansible-role-${ROLE_NAME} fabiorphp.${ROLE_NAME}
  - cd fabiorphp.${ROLE_NAME}

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
