---
language: python
services: docker

env:
  global:
    - ROLE_NAME: consul

install:
  - pip install -r requirements.txt

before_script:
  - cd ../
  - mv ansible-role-${ROLE_NAME} fabiorphp.${ROLE_NAME}
  - cd fabiorphp.${ROLE_NAME}

script:
  - molecule test
