---
- name: create group
  group:
    name: "{{ consul_group }}"
    state: present

- name: create user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: true
    state: present

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  with_items:
    - "{{ consul_bin_dir }}"
    - "{{ consul_config_dir }}"
    - "{{ consul_configd_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_run_dir }}"

- name: install dependencies
  package:
    name: unzip
    state: present

- name: check if installed
  stat:
    path: "{{ consul_bin_dir }}/consul"
  register: install_result

- name: download binary
  unarchive:
    src: "{{ consul_bin_url }}"
    dest: "{{ consul_bin_dir }}"
    remote_src: true
  when: install_result.stat.exists == False

- name: create configuration
  template:
    src: "config.json.j2"
    dest: "{{ consul_config_dir }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0600

- name: register systemd service
  template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: 0600

- name: enabled systemd service
  service:
    name: consul
    state: "{{ consul_systemd_state }}"
    enabled: "{{ consul_systemd_enabled }}"
